# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de4cf5892a59e1301e867b7da1bc667434e82c8ada22fe618aa8defa4a3f13c9ada045a62810edbe62c2456f2e085060be359f84051afd90ab7396032efa9feb

test:
  secret_key_base: 25b839c680942483beb7dee2bf1172bd3c9f2f56d3a7cca422da54620c2c9ad4605237de30f970176cf713e04c6316645e41307c6ac7c9ee68039ee8e56d725e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
